print("Listas em Python")
# uma lista começa com o indicie zero na primeira posição
lista = ['Maria','João','José','Leda','Pedro','Tereza']
print('imprime toda  lista')
print(lista[:])
print('imprime elemento indice 3')
print(lista[3])
print('imprime segundo elemento de trás para frente')
print(lista[-2])
print('imprime um intervalo antes do elemento')
print(lista[0:3])
print('imprime após um elemento')
print(lista[2:])
print('imprime antes de um elemento')
print(lista[:2])
print('adiciona um elemento')
lista.append('Sandra')
print(lista[:])
print('inserindo em uma determinada posição')
lista.insert(2,'Sandra')
print(lista[:])
print('adiciona uma nova lista a lista existente')
lista.extend(['1','2'])
print(lista[:])
print('procurando a posição de um elemento na lista')
print(lista.index('Leda'))
print('pesquisar se um elemento existe ou não em uma lista retorna true ou false')
print('Pedro' in lista)
print('cria uma  lista com tipos diferentes')
lista2 = ['Maria',2,2.3,True]
print(lista2[:])
print('removendo um elemento')
lista.remove('Maria')
print(lista[:])